# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudyWCDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudyWCDB
  pod 'WCDB.swift'

  target 'StudyWCDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudyWCDBUITests' do
    # Pods for testing
  end

end
